version: 1

labels:
  # 브랜치 기반
  - label: "⭐ Feature"
    branch: "(feat|feature)/.*"

  - label: "🎨 Style"
    branch: "(style)/.*"

  - label: "⚙️ Init"
    branch: "(init)/.*"

  - label: "🔄️ Refactor"
    branch: "(refactor)/.*"

  - label: "🔗 API"
    branch: "(api)/.*"

  - label: "🔨 Fix"
    branch: "(fix|hotfix)/.*"

  - label: "🚀 Deploy"
    branch: "(deploy|release)/.*"

  # 작성자 기반
  - label: "🐯 채원"
    authors:
      - "chaewon41"

  - label: "🐲 현종"
    authors:
      - "Navi-Up"

  - label: "🐺 혜원"
    authors:
      - "ehye1"

  - label: "🐼 우찬"
    authors:
      - "pwc2002"

  - label: "🦊 진석"
    authors:
      - "jin-evergreen"
